---

- name: "Run apt-get update"
  apt:
    update_cache: no

- name: "Update all packages to the latest version"
  apt:
    upgrade: dist
  when: os_name == "ubuntu"

- name: "Install latest version of icinga agent"
  apt:
    name: icinga2
    state: present
    install_recommends: yes
  notify:
    - restart icinga2

- name: "Create host configuration file - non DLT nodes"
  template:
    src: add-host.j2
    dest: /etc/icinga2/conf.d/{{ inventory_hostname }}.conf
    owner: nagios
    group: nagios
    mode: 0644
  when: os_name == "ubuntu"

- name: "Create host configuration file - DLT nodes only"
  template:
    src: add-dlt-node.j2
    dest: /etc/icinga2/conf.d/{{ inventory_hostname }}.conf
    owner: nagios
    group: nagios
    mode: 0644
  when: os_name == "debian"

- name: "delete old hosts.conf file on DLT nodes"
  file:
    path: /etc/icinga2/conf.d/hosts.conf
    state: absent
  when: os_name == "debian"

- name: "delete old constants.conf file on DLT nodes"
  file:
    path: /etc/icinga2/constants.conf
    state: absent
  when: os_name == "debian"

- name: "Create new constants configuration file - DLT nodes only"
  template:
    src: constants.conf.j2
    dest: /etc/icinga2/constants.conf
    owner: nagios
    group: nagios
    mode: 0644
  when: os_name == "debian"

- name: "Change internal_icinga2_server_host_ip if client ip is inside vlan 20"
  set_fact:
    internal_icinga2_server_host_ip: "{{ hostvars[groups.icinga2_server[0]].host_ip_vlan_20 }}"
  when: host_vlan == "20"

- name: "Change internal_icinga2_server_host_ip if client ip is inside vlan 60"
  set_fact:
    internal_icinga2_server_host_ip: "{{ hostvars[groups.icinga2_server[0]].host_ip_vlan_60 }}"
  when: host_vlan == "60"

- name: "Change internal_icinga2_server_host_ip if client ip is inside vlan 70"
  set_fact:
    internal_icinga2_server_host_ip: "{{ hostvars[groups.icinga2_server[0]].host_ip_vlan_70 }}"
  when: host_vlan == "70"

- name: "Add master to client /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item['ip'] }}.*$"
    line: "{{ item['ip'] }}\t{{ item['names'] | join(' ') }}"
    state: present
  with_items:
  - ip: "{{ internal_icinga2_server_host_ip }}"
    names:
    - "{{ internal_icinga2_server_container_name }}"
    - "{{ internal_icinga2_server_host_name }}"

- name: "Delete local zones.conf file"
  file:
    path: /etc/icinga2/zones.conf
    state: absent
  notify:
    - restart icinga2

- name: "Copy file to local"
  fetch:
    src: /etc/icinga2/conf.d/{{ inventory_hostname }}.conf
    dest: /tmp/{{ inventory_hostname }}.conf
