
- block:

  - name: resolvconf install
    apt:
      name: resolvconf
      state: present

  - name: "Change internal_icinga2_server_host_ip if client ip is inside vlan 70"
    set_fact:
      internal_freeipa_ldap_server_ip: "{{ hostvars[groups.ldapserver[0]].host_ip_vlan_70 }}"
      internal_freeipa_ldap_server_replica_ip: "{{ hostvars[groups.ldapserver[1]].host_ip_vlan_70 }}"
    when: host_vlan == "70"

  - name: "Add master to client /etc/hosts"
    lineinfile:
      dest: /etc/hosts
      regexp: "^{{ item['ip'] }}.*$"
      line: "{{ item['ip'] }}\t{{ item['names'] | join(' ') }}"
      state: present
    with_items:
    - ip: "{{ internal_freeipa_ldap_server_ip }}"
      names:
      - "{{ internal_freeipa_ldap_server_hostname }}"

  - name: Set the time zone
    timezone:
      name: Europe/Vienna

  - name: "Add master to client /etc/resolve.conf"
    lineinfile:
      dest: /etc/resolvconf/resolv.conf.d/head
      regexp: "^{{ item['name'] }}.*$"
      line: "{{ item['name'] }}\t{{ item['ip'] | join(' ') }}"
      state: present
    with_items:
    - name: "nameserver"
      ip:
      - "{{ internal_freeipa_ldap_server_ip }}"

  - name: "Add master to client /etc/resolve.conf"
    lineinfile:
      dest: /etc/resolvconf/resolv.conf.d/head
      regexp: "^{{ item['name'] }}.*$"
      line: "{{ item['name'] }}\t{{ item['ip'] | join(' ') }}"
      state: present
    with_items:
    - name: "nameserver"
      ip:
      - "{{ internal_freeipa_ldap_server_replica_ip }}"
    notify:
      - start resolvconf

  delegate_to: "{{ internal_ipa_client_ip }}"
