- hosts: "{{ icinga_client_name }}"
  remote_user: "{{ admin.user }}"
  gather_facts: no
  become: yes

  vars:
    icinga_client_name:  
    icinga_client_ip:    
  roles:
    - icinga2_client_installation
