---

- name: Install docker engine
  apt:
    name: docker.io
    state: present
  notify:
    - stop docker
    - start docker

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: Modify the user '{{ admin.user }}'. Appending the group 'docker' to the user's groups
  user:
    name: "{{ admin.user }}"
    groups: docker
    append: yes
    state: present
  notify:
    - stop docker
    - start docker

- name: Install python3-pip on ubuntu
  apt:
    name: python3-pip
    state: present


- name: Install ansible docker module
  pip:
    name: docker-py
    executable: pip3
