---
# tasks file for roles/bastion_server

- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - nginx

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  changed_when: false

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubectl

- name: Install Container Dashboeard Package
  apt:
    name: cockpit-dashboard
    state: present

- name: Ensure to remove default files for nginx
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  tags:
  - skip_ansible_lint

- name: Configure nginx conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/nginx.conf
  notify:
    - stop nginx
    - start nginx
