- name: Set fact for ldap_server from the host group 'ldapserver'
  set_fact:
    internal_ldap_server_master01_domain: "{{ hostvars[groups.ldapserver[0]].host_domain }}"
    internal_ldap_server_master01_ip: "{{ hostvars[groups.ldapserver[0]].host_ip }}"
    internal_ldap_server_master01_dns: "{{ hostvars[groups.ldapserver[0]].ldap_server_dns }}"
    internal_host_user: "{{ admin.user }}"
    internal_ldap_client_ip: "{{ hostvars[groups.deployment_server[0]].host_ip }}"

- name: Set fact for docker from the host group 'ldapserver'
  set_fact:
    internal_ldap_server_docker_name: "{{ hostvars[groups.ldapserver[0]].base.docker.ldap_server.container_name }}"
    internal_ldap_server_docker_image: "{{ hostvars[groups.ldapserver[0]].base.docker.ldap_server.image }}"
    internal_ldap_server_docker_tag: "{{ hostvars[groups.ldapserver[0]].base.docker.ldap_server.tag }}"
    internal_docker_restart_policy: "{{ hostvars[groups.ldapserver[0]].base.docker.restart_policy }}"


- name: Set fact for docker from the host group 'ldapserver'
  set_fact:
    internal_ldap_server_admin_pass: "{{ ldap_server.password }}"
