
- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Upgrade all apt packages
  apt:
    upgrade: dist
    force_apt_get: yes

- name: install rsyslog server
  apt:
    name: rsyslog
    state: present

- name: "Copy logstash rsyslog config file"
  template:
    src: rsyslog-logstash.conf.j2
    dest: /etc/rsyslog.d/logstash.conf

- name: "Copy rsyslog config file"
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf

- name: "Make sure that the vm_max_map_count kernel"
  shell: >
    sudo sysctl -w vm.max_map_count=262144
  changed_when: false
